blur: {
  method = "dual_kawase";
  strength = 4;
  background = false;
  background-frame = false;
  background-fixed = false;
}

backend = "glx"

shadow=false;

wintypes:
{
 dock = { shadow = false; };
 dnd = { shadow = false; };
 tooltip = { shadow = false; };
 menu        = { opacity = false; };
 dropdown_menu = { opacity = false; };
 popup_menu    = { opacity = false; };
 utility       = { opacity = false; };
};

opacity-rule = [ "100:_NET_WM_STATE@[0]:32a = '_NET_WM_STATE_FULLSCREEN'",
"100:_NET_WM_STATE@[1]:32a = '_NET_WM_STATE_FULLSCREEN'",
"100:_NET_WM_STATE@[2]:32a = '_NET_WM_STATE_FULLSCREEN'",
"100:_NET_WM_STATE@[3]:32a = '_NET_WM_STATE_FULLSCREEN'",
"100:_NET_WM_STATE@[4]:32a = '_NET_WM_STATE_FULLSCREEN'" ];


corner-radius = 8
rounded-corners-exclude = [
    "class_g = 'dwm'",
    "class_g = 'dmenu'",
];
